CREATE TABLE INVENTORY_MNGMENT.ITEM (
ITEM_ID VARCHAR(30) PRIMARY KEY ,
ITEM_NAME VARCHAR(50),
ITEM_DESCRIPTION VARCHAR (100)
);


CREATE TABLE INVENTORY_MNGMENT.STORE (
STORE_ID VARCHAR(30) PRIMARY KEY ,
STORE_NAME VARCHAR(50),
STORE_LOCATION VARCHAR (50),
CONTACT_NUMBER INT
);



CREATE TABLE INVENTORY_MNGMENT.SUPPLIER 
(
    SUPPLIER_ID VARCHAR(20),
    SUPPLIER_NAME VARCHAR(100),
	PRIMARY KEY (SUPPLIER_ID)
);



CREATE TABLE INVENTORY_MNGMENT.STORE_SUPPLIER 
(
    SUPPLY_ID VARCHAR(30) PRIMARY KEY,
    SUPPLY_DATE DATE,
    STORE_ID VARCHAR(30),
    ITEM_ID VARCHAR(30),
    SUPPLIER_ID VARCHAR(20),
    ITEM_COUNT INT,
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID) ,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);



CREATE TABLE INVENTORY_MNGMENT.STORE_INVENTORY 
(
ITEM_ID VARCHAR(30),
STORE_ID VARCHAR(30),
TOTAL_ITEM INT,
ITEM_SOLD INT,
ITEM_LEFT INT,
PRIMARY KEY (ITEM_ID,STORE_ID)
);
