LOAD DATA INFILE 'E:\Item.csv' 
INTO TABLE item
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'E:\Supplier.csv' 
INTO TABLE Supplier  
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'E:\Store.csv' 
INTO TABLE Supplier  
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'E:\Store_Supplier.csv' 
INTO TABLE Store_Supplier  
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'E:\store_inventory.csv' 
INTO TABLE Store_Supplier  
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;